env: prod

app_project: captainbarnius
app_family: tools
app_name: stockx-billbee-bridge

mon:
  logger:
    level: info
    format: console
    output:
      file: 'application-log.log'
    timestamp_format: 15:04:05.000
    tags: {}

http_client_retry_count: 3
http_client_request_timeout: 30s

## Please fill information from here on ##
wait_before_import_seconds: 60

# If you use gmail to send your sales via email you need to let this app access your google email
# see: https://kb.synology.com/en-global/SRM/tutorial/How_to_use_Gmail_SMTP_server_to_send_emails_for_SRM

# for gmail for example: smtp.gmail.com
smtp_server: ""

# for gmail for example: 587
smtp_port: 0

# your email adress
smtp_email: ""

# your email password
smtp_password: ""

# According to the billbee docs you have to provide here the correct email endpoint
billbee_email_endpoint: "SHOP_ID-json-orderimport@inbound.billbee.de"

# wait time after every sent email
billbee_email_delay_seconds: 5

# applied on each orderItem. See order_items[n].taxrate
vat_rate: 0

#see comment
importComment: "0"

# see internal_note
internalNote: "Generated from Stockx Bridge Application"

# see currency_code - default EUR
stockx_currency: 'EUR'

# Possible Values:
#  - paypal
#  - vorkasse
#  - überweisung
#  - banküberweisung
#  - kreditkarte
#  - nachnahme
#  - sofortüberweisung
#  - barzahlung
#  - rechnung
stockx_payout_method: 'paypal'

# 7 = Abgeschlossen. See https://hilfe.billbee.io/article/392-json-e-mail-bestellimport
stockx_order_status_id: 7