env: prod

app_project: captainbarnius
app_family: tools
app_name: billbee-importer

log:
  handlers:
    main:
      formatter: json
      level: info
      timestamp_format: '15:04:05:000'
      type: iowriter
      writer: file
      path: 'application.log'

http_client:
  retry_count: 3
  request_timeout: 30s

## Please fill information from here on ##
# If you use gmail to send your sales via email you need to let this app access your google email
# see: https://kb.synology.com/en-global/SRM/tutorial/How_to_use_Gmail_SMTP_server_to_send_emails_for_SRM

# for gmail for example: smtp.gmail.com
smtp_server: ""

# for gmail for example: 587
smtp_port: 0

# your email adress
smtp_email: ""

# your email password
smtp_password: ""

# wait time after every sent email
billbee_email_delay_seconds: 5

# According to the billbee docs you have to provide here the correct email endpoint
stockx_billbee_email_endpoint: "SHOP_ID-json-orderimport@inbound.billbee.de"
alias_billbee_email_endpoint: "SHOP_ID-json-orderimport@inbound.billbee.de"

# applied on each orderItem. See order_items[n].taxrate
stockx_vat_rate: 0
alias_vat_rate: 0

#see comment
stockx_import_comment: "0"
alias_import_comment: "0"

# see internal_note
stockx_internal_note: "Generated from Billbee Importer"
alias_internal_note: "Generated from Billbee Importer"

# see currency_code - default EUR
stockx_currency: 'EUR'
alias_currency: 'EUR'

# Possible Values:
#  - paypal
#  - vorkasse
#  - überweisung
#  - banküberweisung
#  - kreditkarte
#  - nachnahme
#  - sofortüberweisung
#  - barzahlung
#  - rechnung
stockx_payout_method: 'paypal'
alias_payout_method: 'paypal'

# 7 = Abgeschlossen. See https://hilfe.billbee.io/article/392-json-e-mail-bestellimport
stockx_order_status_id: 7
alias_order_status_id: 7

alias_vat_id: 'NL 826259716B01'
stockx_vat_id: ''